### ISSUE TITLE
ChatApp.jsx error after login 

### ISSUE THREAD

**Issue by rexsllemel** [ganraj21/Dental_Clinic#1]
After registering an account and logging in, the web page is blank (white page). When inspecting, I have this following error on the console:

`Uncaught TypeError: Cannot read properties of undefined (reading '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED')
    at 356 (react-bootstrap.min.js:2:3088)
    at o (react-bootstrap.min.js:2:3818)
    at 373 (react-bootstrap.min.js:2:3600)
    at o (react-bootstrap.min.js:2:3818)
    at react-bootstrap.min.js:2:7214
    at react-bootstrap.min.js:2:113613
    at react-bootstrap.min.js:2:113619
    at react-bootstrap.min.js:2:298
    at react-bootstrap.min.js:2:320
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
react-dom.development.js:22839 Uncaught SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at ChatApp.jsx:15:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at react-dom.development.js:26769:1
react-dom.development.js:18687 The above error occurred in the <ChatApp> component:

    at ChatApp (http://localhost:3000/static/js/bundle.js:1742:81)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:49512:5)
    at Routes (http://localhost:3000/static/js/bundle.js:49961:5)
    at App
    at Router (http://localhost:3000/static/js/bundle.js:49892:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:47889:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
react-dom.development.js:12056 Uncaught SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at ChatApp.jsx:15:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at react-dom.development.js:26769:1`

**Comment by ganraj21** [comment]
web page is blank because I haven't made the structure of Chatting feature. After login this code is navigating to chat page so may be some route issue will be there.

**Comment by ganraj21** [comment]
I resolved this issue temporarily. When Chatting layout structure is ready then I will fix it.

**Comment by rexsllemel** [comment]
Thank you so much!

**Comment by ganraj21** [comment]
> I resolved this issue temporarily. When Chatting layout structure is ready then I will fix it.
